### ISSUE TITLE
UFW lockdown script

### ISSUE THREAD

**Issue by pjv** [microram/ee4-tools#2]
Interesting project.

I was just looking at your [cloudflare UFW script](https://github.com/microram/ee4-tools/blob/master/common/cloudflare-ufw) and I noticed that it sets up a rule to whitelist the cloudflare IP's. I don't know how often it happens, but those can (and do) change sometimes. Do you have a cron somewhere that updates that UFW rule periodically?

**Comment by microram** [comment]
I place the cloudflare-ufw script in /etc/cron.weekly on my own server. I will update the docs to note that.
